import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Sidebar} from "@/components/molecules/Navigation/Sidebar";
import Topbar from "@/components/molecules/Navigation/Topbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Purshotam Profiles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex">
        <Sidebar />
        <div className="w-full bg-slate-50">
        <section>
          {children}
        </section>
        </div>
        </main>
      </body>
    </html>
  );
}
